- hosts: bootcamp
  remote_user: root
  become: yes
  tasks:
    - name: install Java 8
      yum:
        name: java-1.8.0-openjdk
        state: present  
    - name: install Maven
      yum:
        name: maven
        state: latest